{"Message":"An error has occurred.","ExceptionMessage":"Exception of type 'Itinero.Exceptions.RouteNotFoundException' was thrown.","ExceptionType":"Itinero.Exceptions.RouteNotFoundException","StackTrace":"   at Itinero.Result`1.get_Value()\r\n   at Itinero.RouterBaseExtensions.Calculate(RouterBase router, IProfileInstance profile, Coordinate source, Coordinate target, CancellationToken cancellationToken)\r\n   at Itinero.RouterBaseExtensions.Calculate(RouterBase router, IProfileInstance profile, Coordinate source, Coordinate target)\r\n   at RoutingAPI.Controllers.RouterController.GetRoute(String profile, Single startLat, Single startLon, Single endLat, Single endLon) in D:\\Andrei\\Scoala\\LICENTA\\TCCC\\RouteComputingServer\\RoutingAPI\\Controllers\\RouterController.cs:line 38\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}